openapi: 3.0.0
servers:
  # Added by API Auto Mocking Plugin
  - description: SwaggerHub API Auto Mocking
    url: https://virtserver.swaggerhub.com/LEOREISLAR/pet-api/1.0.0
  - url: 'https://my-json-server.typicode.com/LReiz/openapi-spike'
info:
  description: >-
    This is a sample server Petstore server. For this sample, you can use the api key
    `special-key` to test the authorization filters.
  version: 1.0.0
  title: OpenAPI Posts
  license:
    name: Apache-2.0
    url: 'https://www.apache.org/licenses/LICENSE-2.0.html'
tags:
  - name: posts
    description: Everything about Posts
paths:
  /posts:
    get:
      tags:
        - posts
      summary: Get posts
      description: ''
      operationId: getPosts
      responses:
        '200':
          description: successful operation
          content:
            application/xml:
              schema:
                $ref: '#/components/schemas/Post'
            application/json:
              schema:
                $ref: '#/components/schemas/Post'
    post:
      tags:
        - posts
      summary: Add post
      description: ''
      operationId: addPost
      responses:
        '201':
          description: successful operation
          content:
            application/xml:
              schema:
                $ref: '#/components/schemas/Post'
            application/json:
              schema:
                $ref: '#/components/schemas/Post'
        '405':
          description: Invalid input
      requestBody:
        $ref: '#/components/requestBodies/Post'
components:
  requestBodies:
    Post:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Post'
        application/xml:
          schema:
            $ref: '#/components/schemas/Post'
      description: Just a Post
      required: true
  schemas:
    Post:
      title: a Post
      description: A post on social media
      type: object
      required:
        - id
        - title
      properties:
        id:
          type: integer
          format: int64
        title:
          type: string
          example: this is the title
      xml:
        name: Post
